set -o vi

GREEN="\[$(tput setaf 2)\]"
DBLUE="\[$(tput setaf 19)\]"
LBLUE="\[$(tput setaf 93)\]"
YELLOW="\[$(tput setaf 11)\]"
LGREY="\[$(tput setaf 243)\]"
RED="\[$(tput setaf 58)\]"
RESET="\[$(tput sgr0)\]"

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="${GREEN}:$(pwd)${RESET}> "

source ~/notes
